import React from 'react';
import { useApp } from '../context/AppContext';
import { Task, TaskType } from '../types';
import { PlayCircle, ClipboardList, Gamepad2, Download } from 'lucide-react';
import { Link } from 'react-router-dom';

const MOCK_TASKS: Task[] = [
  { id: '1', title: 'Smart AI Quiz', description: 'Answer generic trivia generated by Gemini AI.', reward: 5, type: TaskType.AI_QUIZ, icon: 'ai', cta: 'Play Now', color: 'bg-purple-100 text-purple-600' },
  { id: '2', title: 'Market Survey', description: 'Complete a 2 min survey about shopping habits.', reward: 25, type: TaskType.SURVEY, icon: 'survey', cta: 'Start', color: 'bg-blue-100 text-blue-600' },
  { id: '3', title: 'Watch Promo Video', description: 'Watch a 30 second ad completely.', reward: 2, type: TaskType.VIDEO, icon: 'video', cta: 'Watch', color: 'bg-red-100 text-red-600' },
  { id: '4', title: 'Install Cred App', description: 'Install and register to get instant bonus.', reward: 50, type: TaskType.SURVEY, icon: 'download', cta: 'Install', color: 'bg-emerald-100 text-emerald-600' },
];

const Tasks = () => {
  const { addBalance } = useApp();

  const handleTaskClick = (task: Task) => {
    if (task.type === TaskType.VIDEO) {
      const confirm = window.confirm(`Watch video for ₹${task.reward}?`);
      if (confirm) {
        setTimeout(() => {
          addBalance(task.reward, `Task: ${task.title}`);
          alert(`Reward Added! You earned ₹${task.reward}`);
        }, 2000);
      }
    } else if (task.type === TaskType.SURVEY) {
        alert("Redirecting to survey partner...");
    }
  };

  const getIcon = (type: string) => {
    switch (type) {
        case 'ai': return <Gamepad2 size={24} />;
        case 'video': return <PlayCircle size={24} />;
        case 'download': return <Download size={24} />;
        default: return <ClipboardList size={24} />;
    }
  };

  return (
    <div className="p-6">
      <h1 className="text-2xl font-bold text-slate-800 mb-6">Task Marketplace</h1>
      
      <div className="space-y-4">
        {MOCK_TASKS.map((task) => (
          <div key={task.id} className="bg-white p-4 rounded-2xl shadow-sm border border-slate-100 flex items-center justify-between">
             <div className="flex items-center gap-4">
                <div className={`w-12 h-12 rounded-xl flex items-center justify-center ${task.color}`}>
                    {getIcon(task.icon)}
                </div>
                <div>
                    <h3 className="font-bold text-slate-800 text-sm">{task.title}</h3>
                    <p className="text-xs text-slate-400 mt-1 max-w-[140px] truncate">{task.description}</p>
                </div>
             </div>
             
             {task.type === TaskType.AI_QUIZ ? (
                <Link to="/quiz" className="bg-emerald-50 text-emerald-700 px-4 py-2 rounded-lg text-xs font-bold border border-emerald-100">
                    {task.cta}
                </Link>
             ) : (
                <button 
                    onClick={() => handleTaskClick(task)}
                    className="bg-slate-50 hover:bg-emerald-50 text-slate-600 hover:text-emerald-700 px-4 py-2 rounded-lg text-xs font-bold border border-slate-200 hover:border-emerald-200 transition-colors"
                >
                    +₹{task.reward}
                </button>
             )}
          </div>
        ))}
      </div>
      
      <div className="mt-8 bg-indigo-50 border border-indigo-100 rounded-xl p-4 text-center">
         <p className="text-indigo-800 font-medium text-sm">More tasks unlock at 12:00 PM</p>
      </div>
    </div>
  );
};

export default Tasks;